
INSERT INTO public.msg_board_user (id, display_name, name, password, profile_file_name) VALUES (-1, 'Rohan', 'Rohan Ayub', 'Hello123', '/Users/rohanayub/Downloads/user_blank.png');
INSERT INTO public.msg_board_user (id, display_name, name, password, profile_file_name) VALUES (-17, 'TestDelete', 'Delete', 'Delete', '/Users/rohanayub/Downloads/user_blank.png');
INSERT INTO public.thread (id, thread_description, thread_name) VALUES (-2, 'Say hello and tell us a bit about yourself', 'Introduce Yourself');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-3, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-4, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-5, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-6, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-7, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-8, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-9, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-10, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-11, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.post (id, post_content, time_of_post, username_of_poster) VALUES (-12, 'Hello', '12/12/12 12:12 AM', 'Rohan');
INSERT INTO public.permissions (id, key, permission_name) VALUES (-13, 'PERM_CREATE_THREAD', 'Create Thread');
INSERT INTO public.permissions (id, key, permission_name) VALUES (-14, 'PERM_EDIT_USR', 'Edit User');
INSERT INTO public.permissions (id, key, permission_name) VALUES (-15, 'PERM_EDIT_POST', 'Edit Post');
INSERT INTO public.permissions (id, key, permission_name) VALUES (-16, 'PERM_DELETE_POST', 'Delete Post');
INSERT INTO public.msg_board_user_permissions (msg_board_user_id, permissions_id) VALUES (-1, -15);
INSERT INTO public.msg_board_user_permissions (msg_board_user_id, permissions_id) VALUES (-17, -16);